dist: trusty
language: node_js
node_js:
  - '7'

addons:
  sonarqube:
    organization: 'recuencojones-github'
    branches:
      - develop

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:coverage
  - sonar-scanner

